docs(builder): add ci scripts
ng-easy/platform pull request #614
Opened 2022-07-14 15:17 UTC by johannesschobel

added my ci scripts (matrix and individual) to the readme file (see #599 )

2022-07-15 10:25 UTC, samuelfernandez requested changes
@johannesschobel some comments on my side, thanks for the contrib!

2022-07-15 10:25 UTC, samuelfernandez commented on libs/builders/src/semantic-release/README.md
> +You can also use a `Matrix Setup` for your projects to be released. This works as follows:
**issue** Friend, though this works, it is not something I'd like to promote. The reason is that it relies on hardcoding dependencies, something that the builder is actually doing (when it works well).

**suggestion** Would you mind removing the matrix example? Thanks!

2022-07-15 10:25 UTC, samuelfernandez commented on libs/builders/src/semantic-release/README.md
> +        uses: ng-easy/npm-setup@v2
**nitpick** We can add the `nx-key` param so as to benefit from local cache of the build process

```suggestion
        uses: ng-easy/npm-setup@v2
        with:
          nx-key: build
```

2022-07-15 10:25 UTC, samuelfernandez commented on libs/builders/src/semantic-release/README.md
> +        run: npx nx run ${{ github.event.inputs.project }}:build
**question** could you make it work with ` mansagroup/nrwl-nx-action@v2`? In theory you could use the same interpolation approach when passing it to an input

2022-07-15 18:15 UTC, johannesschobel commented
i will take a look at it, of course!

2022-07-15 19:00 UTC, johannesschobel commented on libs/builders/src/semantic-release/README.md
> +        uses: ng-easy/npm-setup@v2
of course i will add this

2022-07-16 08:44 UTC, samuelfernandez requested changes
Sorry, one last comment, thanks for the patience!

2022-07-16 08:44 UTC, samuelfernandez commented on libs/builders/src/semantic-release/README.md
> +You can also use the `Inputs` feature provided by `GitHub` to create a user-interface that lets you select a specific project to be released.
One additional comment I've realized about. This approach can cause a problem if projects are dependent. For example, imagine that there are changes to `project-a` and `project-b`, `project-b` depends on `project-a`, and you only release `project-b`. The released package will have the dependency on the old version, and might break. So we should clarify that:

```suggestion
If the packages don't depend on each other, you can also use the `Inputs` feature provided by `GitHub` to create a user-interface that lets you select a specific project to be released. If there were dependent, previous approach will take care of the dependencies releasing packages in order.
```

2022-07-18 07:00 UTC, johannesschobel commented
Dear @samuelfernandez ,
thanks for the suggestion - i have added the additional information.

2022-07-19 14:50 UTC, samuelfernandez approved these changes
Great! Let's merge this one

2022-07-19 14:50 UTC, merged

2022-07-23 05:23 UTC, samuelfernandez commented
:tada: This PR is included in version **@ng-easy/eslint-config@4.5.25** :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ng-easy/eslint-config/v/4.5.25) :package::rocket:
- [GitHub release](https://github.com/ng-easy/platform/releases/tag/%40ng-easy/eslint-config%404.5.25) :package::rocket:

2022-07-23 05:24 UTC, samuelfernandez commented
:tada: This PR is included in version **@ng-easy/prettier-config@5.0.29** :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ng-easy/prettier-config/v/5.0.29) :package::rocket:
- [GitHub release](https://github.com/ng-easy/platform/releases/tag/%40ng-easy/prettier-config%405.0.29) :package::rocket:

2022-07-23 05:25 UTC, samuelfernandez commented
:tada: This PR is included in version **@ng-easy/image-config@5.1.19** :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ng-easy/image-config/v/5.1.19) :package::rocket:
- [GitHub release](https://github.com/ng-easy/platform/releases/tag/%40ng-easy/image-config%405.1.19) :package::rocket:

2022-07-23 05:25 UTC, samuelfernandez commented
:tada: This PR is included in version **@ng-easy/image-optimizer@5.1.19** :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ng-easy/image-optimizer/v/5.1.19) :package::rocket:
- [GitHub release](https://github.com/ng-easy/platform/releases/tag/%40ng-easy/image-optimizer%405.1.19) :package::rocket:

2022-07-23 05:26 UTC, samuelfernandez commented
:tada: This PR is included in version **@ng-easy/image@5.1.19** :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ng-easy/image/v/5.1.19) :package::rocket:
- [GitHub release](https://github.com/ng-easy/platform/releases/tag/%40ng-easy/image%405.1.19) :package::rocket:

2022-07-23 05:27 UTC, samuelfernandez commented
:tada: This PR is included in version **@ng-easy/builders@9.1.3** :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ng-easy/builders/v/9.1.3) :package::rocket:
- [GitHub release](https://github.com/ng-easy/platform/releases/tag/%40ng-easy/builders%409.1.3) :package::rocket: